#install.packages("RMySQL")
#library(RMySQL)

ucsc_dbs <- dbConnect(MySQL(), user="genome", host="genome-mysql.cse.ucsc.edu")
dbGetQuery(ucsc_dbs, "show databases;")
hg19_db <- dbConnect(MySQL(), user="genome", host="genome-mysql.cse.ucsc.edu", db="hg19")
dbListFields(hg19_db, "affyU133Plus2")
count_result <- dbGetQuery(hg19_db, "select count(*) from affyU133Plus2")
print(count_result)
query <- dbSendQuery(hg19_db, "select tName from affyU133Plus2 where bin=1")
first_batch <- fetch(query, 3)
print(nrow(result))
dbClearResult(query)
dbDisconnect(hg19_db)
dbDisconnect(ucsc_dbs)

